### ISSUE TITLE
Write that big endian is supported.

### ISSUE THREAD

**Issue by karamellpelle** [nmwsharp/happly#19]
_README.md_ says: "_the code assumes the platform is little-endian._" under "Known issues", but [_happly.h_ says that big endian is supported](https://github.com/nmwsharp/happly/blob/983e8edf73c515511720f61d3142cb842bc144d9/happly.h#L43). If happly is now supporting big endian platforms, _README.md_ should be changed, I guess.

Thanks for this nice library in just 1 file :)

**Comment by nmwsharp** [comment]
The distinction is that happly currently supports reading/writing big-endian _files_, but might not support running on a big-endian _computer_.

I've updated the readme to make this a little more explicit. Feel free to re-open if you still think something is out of line!
