### ISSUE TITLE
Error after the last commit.

### ISSUE THREAD

**Issue by jkulhanek** [nmwsharp/happly#36]
I am getting the following error:
error: the operand of a pointer dynamic_cast must be a pointer to a complete class type
lines: 954, 997

However, when I roll back to commit 88f79725d32d78e0e637ebf42d8432d519e1c7d0 it works fine.

**Comment by jkulhanek** [comment]
Sorry, same error even with an older version. Could the problem be caused by using CUDA compiler?

**Comment by jkulhanek** [comment]
Last working commit: 14aeff4aa1862e65d0412011a5a1a8c765abb5a0

**Comment by wrvsrx** [comment]
It seems a problem specific to nvcc, I encounter it too.

**Comment by wrvsrx** [comment]
This issue is fixed by #31

**Comment by nmwsharp** [comment]
#31 is now merged! sorry for the slow response 😅
