### ISSUE TITLE
MeshLab fails to read face lists with number of vertices specified by uint

### ISSUE THREAD

**Issue by keenancrane** [nmwsharp/happly#4]
Perhaps not a hapPLY-specific issue, but still seemingly important in terms of common use cases:

hapPLY uses a face specification

`property list uint uint vertex_indices`

but MeshLab expects

`property list uchar uint vertex_indices`

(and chokes on the former).

**Comment by nmwsharp** [comment]
Ah, good catch. The choice of `uint` was pretty arbitrary, I don't see any big downside to just switching to `uchar`  by default throughout if popular software expects it.

**Comment by nmwsharp** [comment]
Changed in 88821b01ba69285fe0f4366ad7cb55e9e10e701d.
